### ISSUE TITLE
Add router image field in IngressController CRD

### ISSUE THREAD

**Issue by kincl** [openshift/cluster-ingress-operator#267]
With 3.x I was using a customized router image to hook into various pieces of the OpenShift router deployment but in 4.x it looks like that integration point has been removed.

I am using UPI and bare-metal and I am planning to move my customizations to a proxy running in front of the cluster ingress controller but I would like to preserve the source IP with the proxy protocol. Currently the only way the Operator enables the proxy protocol is if it determines that it is running on AWS but it would be nice if this option was also exposed in the IngressController CRD.

**Comment by ironcladlou** [comment]
Do you have a strict requirement to use ELB? NLB should provide source IP preservation without imposing PROXY protocol.

**Comment by kincl** [comment]
> Do you have a strict requirement to use ELB? NLB should provide source IP preservation without imposing PROXY protocol.

I don’t use either since I am on-prem

**Comment by ironcladlou** [comment]
Thanks! cc @smarterclayton @knobunc 

@kincl a few bonus questions if you have the time...

* If you can say, what load balancer are you using?
* Are you using the HostNetwork strategy for the ingress controller (this would be the default on bare metal)?
* Would you prefer a NodePort-based strategy to expose the ingress controller vs. host networking?

**Comment by kincl** [comment]
So to back up a bit, ideally we would have a way to change the router image for a router deployment like what we had in 3.x. This let us do some custom enhancements in the image and avoids this load balancer in front of load balancer in front of pod issue.

Our custom changes to the router image include:

* Route annotation to toggle OAuth authentication (using OpenShift's OAuth server) on a route that is http and is edge or reencrypt (this is really interesting and involves using HAProxy with Lua)
* Forcing some specific web security requirements
  * HTTPS-only with HTTP being a redirect to HTTPS
  * Disabling old ciphers (this was done with ROUTER_CIPHERS=modern env var in 3.x)
  * Forcing HSTS header on all responses (This can be enabled on each route with the annotation haproxy.router.openshift.io/hsts_header but we also need to send it back on the default 503 error page for no backends)
* Customized 503 error pages that include our support e-mail address but turning off the default error page on externally-facing load balancers

To answer your questions specifically:

* For this alternative load balancer in front of load balancer solution we would basically just move our customizations into a standalone HAProxy instance in front of the OpenShift router that is deployed with the ingress controller
* We would use the LoadBalancer strategy and then deploy our new load balancer in the cluster as well with .spec.hostNetwork and expose 80 and 443 there and then it's backend would be the OpenShift router
* Specifically for this solution I would probably prefer just a ClusterIP since we will put the other load balancer in the cluster

**Comment by kincl** [comment]
@ironcladlou gentle bump

Did I hijack my own issue here? I apologize for the left turn but as I kept thinking about it, just adding the proxy protocol field would force us to terminate  HTTPS on our other proxy which is going to be more work.
