### ISSUE TITLE
The operator must honor the cluster proxy configuration

### ISSUE THREAD

**Issue by ironcladlou** [openshift/cluster-ingress-operator#270]
### Goal

The ingress-operator itself (not the operand) must honor the cluster proxy configuration.

### Invariants

* The apiserver is always excluded from proxying

### Challenges

* Idiomatic Go libraries tend to rely on http.DefaultTransport (often via http.DefaultClient), which lazily initializes an immutable proxy configuration based on the process environment as of the time of initialization. This makes changing the stdlib default proxy at runtime dangerous given existing clients/connections.

### Solution

Refactor ingress-operator to replace usage of http.DefaultTransport with a transport set up from the cluster proxy configuration.

#### Implications

* Requires refactoring to consolidate client setup closer to operator startup and inject client into various consumers
* Client properties (e.g. timeouts) can be configured more safely in context than the prior defaults (e.g. to prevent cloud API connection issues from hanging the operator.)

#### Teach CVO to inject proxy environment variables into operator deployments.

Given the invariant that the apiserver is always excluded from proxying, it is assumed operators will be able to reach the apiserver to discover the proxy config to be used for any other clients managed by the operator which may be subject to proxying rules. It's not practical to revisit this CVO design aspect in the timeframe we must support proxying.

#### Mutate the http.DefaultClient or http.DefaultTransport at runtime

It's not clear that mutating any of the stateful net/http package variables in this way will be safe at runtime in the face of existing clients and connections. Finding a safe way to make these mutations seems to be a nontrivial effort. Granted a successful implementation, one apparent advantage would be the fix would apply transparently to the libraries we use. However, client connection properties would remain shared across all contexts.

#### Operator sidecar

A sidecar process to the operator could read proxy configuration, render it somehow to a shared volume, and the operator could then configure its own process environment from the shared data in a (hopefully) safe place early during startup. This would have the same overall implications as the http.DefaultClient mutation approach but in a likely safer way.

**Comment by deads2k** [comment]
Why not use the downward API to inject the env vars based on annotation and simply update the annotation from your operator and suicide?

**Comment by bparees** [comment]
> Why not use the downward API to inject the env vars based on annotation and simply update the annotation from your operator and you'll auto-rollout?

i think the concern is w/ how to ensure the env vars are in the operator pod at startup, not the operand pods.

**Comment by bparees** [comment]
oh, i think i get what you're saying @deads2k, because the CVO won't stomp annotations.

**Comment by bparees** [comment]
still seems a bit undesirable that the operator pod would have to come up, recognize a proxy config exists, update its own annotations, and then rollout again.  So all the operator pods would have to double-clutch rollout during install.

**Comment by ironcladlou** [comment]
Regardless of the possibility of CVO propagating proxy information down to the operator, it was decided that apiserver and cloud provider API clients are exempt from proxy configuration entirely. This new set of assumptions invalidates the requirement described by this issue, which is now obsolete.

/close
