### ISSUE TITLE
endpointPublishingStrategy.type is ignored 

### ISSUE THREAD

**Issue by JuozasA** [openshift/cluster-ingress-operator#271]
Trying to change the default ingresscontroller `endpointPublishingStrategy` type to `HostNetwork` since I want to manage LB for routers on Azure myself (I want to lock the ingress access to the cluster by changing Network Security Rules, because if the service type is LoadBalancer (by default), kubernetes keeps changing the rules back to defaults).

Steps:
once OCP is deployed, I edit the ingresscontroller/default in openshift-ingress-operator namespace and add:
```
spec:
  endpointPublishingStrategy:
    type: HostNetwork
```
However the status stays:
```
  endpointPublishingStrategy:
    loadBalancer:
      scope: External
    type: LoadBalancerService
```
and openshift-ingress service router-default stays of type LoadBalancer:
```
$ oc get svc -n openshift-ingress -o wide
NAME                      TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                      AGE       SELECTOR
router-default            LoadBalancer   172.30.111.225   *.*.*.*   80:32184/TCP,443:30618/TCP   15m       ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
router-internal-default   ClusterIP      172.30.91.243    <none>          80/TCP,443/TCP,1936/TCP      15m       ingresscontroller.operator.openshift.io/deployment-ingresscontroller=default
```

Do I need to add anything else? Or it is not possible to change the default and I need to create a new ingresscontroller? if so, how can i disable the default controller so it won't create public facing LB with open access to the cluster?

Installer version I am running is:
```
$ ./openshift-install version
./openshift-install unreleased-master-1359-g665a8608e5383e5b929b6fa8eb6b99da0b6b77d8
built from commit 665a8608e5383e5b929b6fa8eb6b99da0b6b77d8
release image registry.svc.ci.openshift.org/origin/release:4.2
```

Thanks!

**Comment by JuozasA** [comment]
Just saw that endpointPublishingStrategy.type cannot be changed once created. Fixed it buy creating ingresscontroller with name default and providing endpointPublishingStrategy.type after control plane is initialized (UPI)
/close

**Comment by chuyee** [comment]
@JuozasA Hi, I have a quick question: is it still possible to change UPI default ingress controller endpointPublishingStrategy.type from HostNetwork to something else (like NodePortService) in OCP 4.6? Either day-1 or day-2 is fine. Tried many ways including cluster-ingress-02-config.yml with no luck...
