### ISSUE TITLE
Customize router deployment config to disable namespace ownership check

### ISSUE THREAD

**Issue by larhauga** [openshift/cluster-ingress-operator#285]
On OpenShift 3 it was possible to customize the default deployment of the router by adding environment variables with the needed customization. I cannot find a way of doing this with the cluster-ingress-operator, as the CRD does not contain any options for mutating the deployment.

The specific configuration that I need is `ROUTER_DISABLE_NAMESPACE_OWNERSHIP_CHECK`: https://github.com/openshift/router/blob/master/pkg/cmd/infra/router/router.go#L73-L92

The specific problem in question is related to solving "HostAlreadyClaimed" when binding to the same hostname (with different paths) in multiple namespaces.

Is there any other way of configuring the router/operator to add options? Or should the CRD be updated with the options for customizing the router?

**Comment by xavierbaude** [comment]
I also using options : NAMESPACE_LABELS and ROUTE_LABELS in order to use private & public router depending need. Would you also add these option too ?

**Comment by pashok2398** [comment]
In my case we need to rewrite the `X-Forwarded-For` header so i using the custom template in our ocp 4.1 installation from this guide:
https://docs.openshift.com/container-platform/3.3/install_config/router/customized_haproxy_router.html#using-configmap-replace-template
I add the `http-request set-header X-Forwarded-For %[src]` to base template and using it as configMap.
Is there any option to use custom template or any option to rewrite the `X-Forwarded-For` header with annotation?

**Comment by pashok2398** [comment]
Hello. Sorry for my perseverance.
Is there any plans to implement this?
Thanks

**Comment by haoqing0110** [comment]
Same question of how to use custom template in OCP 4.2 ? Any update for this issue?

**Comment by pashok2398** [comment]
> Same question of how to use custom template in OCP 4.2 ? Any update for this issue?

+1

**Comment by larhauga** [comment]
Hi, I have totally forgotten this issue, and for that I am sorry.
It took a while, but we managed to create a enhancement proposal for changing the `ROUTER_DISABLE_NAMESPACE_OWNERSHIP_CHECK` env variable on the router deployment.
https://github.com/openshift/enhancements/blob/master/enhancements/ingress/openshift-route-admission-policy.md

We ran with a custom router during the period where this was not possible, by assigning the default router to a specific node, while having a custom deployment of the router. You can then configure the router as you would like, without having the configuration in the Operator.

If the OpenShift ingress operator does not include it in its CRD you will need to either create a issue/enhancement detailing your use-case. Or you could create a new deployment where you run a custom router with your changes.

If you are coming here looking for enabling the `ROUTER_DISABLE_NAMESPACE_OWNERSHIP_CHECK` environment variable, you can take a look at the new configuration for route admission policy. 
https://docs.openshift.com/container-platform/4.5/networking/routes/route-configuration.html#nw-route-admission-policy_route-configuration
