### ISSUE TITLE
Enhance cluster-ingress-operator to support libvirt

### ISSUE THREAD

**Issue by ahrtr** [openshift/cluster-ingress-operator#299]
Currently cluster-ingress-operator only supports AWS, Azure and GCP.  But in development environment, i.e. CI, libvirt is useful. So it'd better to enhance ingress-operator to support libvirt.

**Comment by jichenjc** [comment]
some to do item: 

[ ] https://github.com/openshift/cluster-ingress-operator/blob/master/cmd/ingress-operator/main.go#L123 not support libvirt, need add a libvirt branch here
