### ISSUE TITLE
[Question] The process of Ingress Operator adding/removing DNS records.

### ISSUE THREAD

**Issue by gyohuangxin** [openshift/cluster-ingress-operator#310]
Some problem about the codes blocks me, when I work on the pull request #308. 

## What we are doing

A new libvirt provider  needs to be implemented in https://github.com/openshift/cluster-ingress-operator/tree/master/pkg/dns.
That provider will need to implement the provider interface:
```
 // Provider knows how to manage DNS zones only as pertains to routing.
 type Provider interface {
	// Ensure will create or update record.
	Ensure(record *iov1.DNSRecord, zone configv1.DNSZone) error

	// Delete will delete record.
	Delete(record *iov1.DNSRecord, zone configv1.DNSZone) error
}
```

Additionally, a new configuration may be needed that is libvirt specific:
See:
https://github.com/openshift/cluster-ingress-operator/blob/f9a372f407212cd2766293d97c820febd6e902d9/cmd/ingress-operator/main.go#L123

## Question

1. In the process of Ingress Conrotoller running, which part of the code calls the Ensure and Delete methods, and when they are called? 

2. I find a [dnscontroller](https://github.com/openshift/cluster-ingress-operator/blob/master/pkg/operator/controller/dns/controller.go) is created and [cluster-ingress-operator/pkg/operator/controller/ingress/dns.go](https://github.com/openshift/cluster-ingress-operator/blob/master/pkg/operator/controller/ingress/dns.go) is implementd. What are the links between the two parts and what they do when some DNS records need added by Ingress?

**Comment by zeenix** [comment]
Kindly ask questions about the PR in the PR comments. If you've work-in-progress patches that you've questions on, you're more than welcome to create WIP PRs, marked as such with `wip: ` prefix in the title of the PR.

/close
