### ISSUE TITLE
Issue using private Load balancer type for ingress operator on azure in OCP 4.2

### ISSUE THREAD

**Issue by aglenn360** [openshift/cluster-ingress-operator#312]
Description of problem:

Has anyone looked at deploying private LB for ingress router yet? https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-enable-ingress-controllers, looks to work on AWS ok but getting issues on azure.

fails against subnet as doesn't exist

cluster63-99qm4-vnet/cluster63-99qm4-node-subnet

the actual subnet that gets created in Azure is worker-subnet not node-subnet, maybe a bug with Naming standards?

Version-Release number of selected component (if applicable):

4.2.0 on Azure

How reproducible:

every time

Steps to Reproduce:
1. Destroy ingress router default and re-create using https://docs.openshift.com/container-platform/4.2/release_notes/ocp-4-2-release-notes.html#ocp-4-2-enable-ingress-controllers

Actual results:

Service for internal loadbalancer sits pending with error 

Events:
  Type     Reason                      Age                  From                Message
  ----     ------                      ----                 ----                -------
  Normal   EnsuringLoadBalancer        2m45s (x9 over 18m)  service-controller  Ensuring load balancer
  Warning  CreatingLoadBalancerFailed  2m45s (x9 over 18m)  service-controller  Error creating load balancer (will retry): failed to ensure load balancer for service openshift-ingress/router-default: ensure(openshift-ingress/router-default): lb(cluster63-99qm4-internal) - failed to get subnet: cluster63-99qm4-vnet/cluster63-99qm4-node-subnet

The subnet 

cluster63-99qm4-vnet/cluster63-99qm4-node-subnet

does not exist the subnets that get created are 

clustername-UID-worker-subnet

clustername-UID-master-subnet

interestingly the NSG for 

clustername-UID-worker-subnet

is called clustername-UID-node-nsg

Expected results:

service starts correctly with an internalLB ip for azure, guessing this should try and apply against clustername-UID-worker-subnet

Additional info: This works ok on AWS just having issues with Azure, also if you re-label the subnet clustername-UID-worker-subnet to clustername-UID-node-subnet this issue is resolved

**Comment by vguar** [comment]
Hi, I have the same problem  on Azure.

**Comment by Miciah** [comment]
This looks like the same issue as https://bugzilla.redhat.com/show_bug.cgi?id=1763727.
Please re-open if I am mistaken.
/close
