### ISSUE TITLE
Documentation not clear about which versions of OpenShift have ingress operator

### ISSUE THREAD

**Issue by Alex2357** [openshift/cluster-ingress-operator#318]
[Here](https://github.com/openshift/cluster-ingress-operator#installing) it says

Every new OpenShift installation has an ingresscontroller named default which can be customized, replaced, or supplemented with additional ingress controllers. To view the default ingress controller, use the oc command:

```
$ oc describe --namespace=openshift-ingress-operator ingresscontroller/default
```

When I run same command on Openshift cluster 3.11 I get this

```
john@alaptop:~/gits/notes$ oc describe --namespace=openshift-ingress-operator ingresscontroller/default
error: the server doesn't have a resource type "ingresscontroller"
john@alaptop:~/gits/notes$ 
```

If I run same command in Minishift which is also 3.11 I get same issue. I can't provide a link at the moment but I have read that ingress support in OpenShift from 3.11. What am I doing wrong?

**Comment by lihongan** [comment]
This command for 4.x only, not for 3.11.

**Comment by Alex2357** [comment]
> This command for 4.x only, not for 3.11.
> Ingresscontroller is not supported in 3.x release.

@lihongan  Thank you very much for the quick response. I'm confused. As I said I have read somewhere on redhat website that OpenShift supports ingress from 3.11. 

In [here](https://blog.openshift.com/kubernetes-ingress-vs-openshift-route/) 

```
Since the release of Red Hat OpenShift 3.10, ingress objects are supported alongside route objects. The Red Hat OpenShift ingress controller implementation is designed to watch ingress objects and create one or more routes to fulfill the conditions specified. 
```

I wanted to do all the steps from the article above, but it failed on `oc new-build java:8~https://github.com/spring-projects/spring-petclinic.git`

```
john@alaptop:~/gits$ oc new-build java:8~https://github.com/spring-projects/spring-petclinic.git
error: the image match "java:8" for source repository "https://github.com/spring-projects/spring-petclinic.git" does not appear to be a source-to-image builder.
```

Another attempt
```
- to attempt to use this image as a source builder, pass "--strategy=source"
- to use it as a base image for a Docker build, pass "--strategy=docker"
john@alaptop:~/gits$

john@alaptop:~/gits$ oc new-build https://github.com/spring-projects/spring-petclinic.git
error: multiple images or templates matched "jee"

The argument "jee" could apply to the following Docker images, OpenShift image streams, or templates:

* Image stream "wildfly" (tag "10.1") in project "openshift"
  Use --image-stream="openshift/wildfly:10.1" to specify this image or template

* Image stream "wildfly" (tag "11.0") in project "openshift"
  Use --image-stream="openshift/wildfly:11.0" to specify this image or template

* Image stream "wildfly" (tag "12.0") in project "openshift"
  Use --image-stream="openshift/wildfly:12.0" to specify this image or template

* Image stream "wildfly" (tag "8.1") in project "openshift"
  Use --image-stream="openshift/wildfly:8.1" to specify this image or template

* Image stream "wildfly" (tag "9.0") in project "openshift"
  Use --image-stream="openshift/wildfly:9.0" to specify this image or template

To view a full list of matches, use 'oc new-build -S jee'
john@alaptop:~/gits$
```

**Comment by JuozasA** [comment]
The blog post refers to Ingress as a Kubernetes object ( https://kubernetes.io/docs/concepts/services-networking/ingress/ ) , IngressController is Cluster Ingress Operator object and is not available in OCP 3.* releases.

Regarding the issues you are having when following the blog post, make sure you perform all steps and if you still get the error, contact the author...

**Comment by ironcladlou** [comment]
As others mentioned, the Ingress operator is part of OpenShift 4 and isn't available in OpenShift 3.
