### ISSUE TITLE
[RFE] Discover number of router replicas based on the number of workers

### ISSUE THREAD

**Issue by e-minguez** [openshift/cluster-ingress-operator#332]
Currently in baremetal environments composed by 3 masters + 1 worker, the number of router replicas is set to 2 so one of the router replicas stays in 'pending' forever. The current workaround is to patch the ingresscontroller as:

```
oc patch -n openshift-ingress-operator ingresscontroller/default --patch '{"spec":{"replicas": 1}}' --type=merge
```

While I agree having 2 routers is the best practice, I'd say it would be nice for that kind of deployments (3+1 in baremetal) to be able to deploy with a single router... then, when more workers are added, increase the number of replicas.

**Comment by ironcladlou** [comment]
It's now possible to bring your own ingress controller definition at install time, which handles the default use case.

Beyond that, I suspect this will become a discussion about integration with the autoscaler.
