### ISSUE TITLE
Suggestion for AWS: use CNAMEs instead of A Alias records in Route53

### ISSUE THREAD

**Issue by Obirah** [openshift/cluster-ingress-operator#364]
Hi,

I already opened a similar issue for the OpenShift installer: https://github.com/openshift/installer/issues/3150

The gist is: I'm suggesting to use a CNAME record instead of an A Alias record for the "*.apps.<cluster-url" DNS record in Route53 on AWS since CNAME records conform to the RFC standard while A Alias records (to my knowledge) do not.

Would that be feasible for the cluster-ingress-operator or are there any big advantages to using the A Alias that I'm just not seeing because I cannot use them in my enterprise environment?

Another feasible approach for me would, if we were able to parameterize the operator so that it uses CNAME instead of A Alias. This way, A Alias could still be the default and the impact of the change would be a bit lower.

**Comment by Obirah** [comment]
A colleague also contributed something similar to the "external-dns" project for plain k8s: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md#can-i-force-externaldns-to-create-cname-records-for-elbalb

**Comment by ironcladlou** [comment]
Interesting. There are also cost considerations (see https://aws.amazon.com/route53/pricing/).

**Comment by ironcladlou** [comment]
(Specifically, queries to ALIAS records mapped to ELBs are free.)

**Comment by Obirah** [comment]
You are right, I discussed it with a colleague a few days ago. Therefore, it possibly would be best to be able to pick between the two choices.
