### ISSUE TITLE
Define custom annotations for LB Service

### ISSUE THREAD

**Issue by eldis80** [openshift/cluster-ingress-operator#524]
Hi,

Is it possible to define own annotations that would get passed to the LB service created by cluster-ingress-operator? Specifically, I'm interested in adding **service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout** to override the default idle timeout (60s) for AWS Classic LB. I know I could add this directly to the created service but we are using gitops for OpenShift configuration and I would prefer to not to modify resources created by operators but instead modify the Ingress (cluster) or IngressController (default) resources.

We currently have OS v4.5.15 installed.

**Comment by Miciah** [comment]
I realize this response is very belated, but this enhancement proposal would add an API for configuring the idle timeout on AWS LBs:  https://github.com/openshift/enhancements/pull/461

Unfortunately I cannot say at this time in which version of OpenShift the enhancement will be implemented.  

There is no general API to tell the operator to set arbitrary annotations on operands.

**Comment by eldis80** [comment]
Thanks for the information. I don't remember if whether we just updated the idle timeouts manually or created the corresponding Service resource with the annotation to set the idle timeout. Anyhow, it's great that a more proper way of setting the idle timeout is coming.
