### ISSUE TITLE
unable to build images locally

### ISSUE THREAD

**Issue by nevidanniu** [openshift/cluster-ingress-operator#536]
Due to base images located in private group, there is no way to build images locally:
```
docker pull registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.6
Error response from daemon: unauthorized: authentication required

docker pull registry.ci.openshift.org/ocp/4.6:base
Error response from daemon: unauthorized: authentication required
```

**Comment by sgreene570** [comment]
As a workaround, you could swap in a centos image for both of the unavailable images.

You could probably also fetch a publicly mirrored ingress-operator image from https://quay.io/repository/openshift/origin-cluster-ingress-operator?tab=info if that's useful to know.
