### ISSUE TITLE
Ingress operator should remove deployment when highAvailability.type changes

### ISSUE THREAD

**Issue by vrutkovs** [openshift/cluster-ingress-operator#86]
By default `highAvailability.type` is set to Cloud, so in BYOR case this should be changed to `UserDefined`. This however doesn't remove the router deployment and the service - currently this needs to be done manually.

The operator should detect that HA type has changed and recreate the deployment automatically

**Comment by michaelgugino** [comment]
I had to delete the ingress-operator, not just the deployment for this to work.
```sh
oc delete deployments -n "openshift-ingress-operator" ingress-operator
oc delete deployments router-default -n "openshift-ingress"
```

**Comment by ironcladlou** [comment]
endpointPublishingStrategy (formerly highAvailability) is now immutable, rendering this bug obsolete.
