### ISSUE TITLE
Bugzilla reference in New Issue template leads to dead end

### ISSUE THREAD

**Issue by nate-duke** [openshift/cluster-ingress-operator#911]
Upon walking through the New Issue workflow on this repo one is encouraged to open a bugzilla but when you eventually get to the bugzilla from that link you're met with:

```
Sorry, entering a bug into the product OpenShift Container Platform has been disabled.

OCP is now accepting bugs in Jira! Open a case with customer support, or file directly in Jira: https://issues.redhat.com/secure/CreateIssueDetails!init.jspa?pid=12332330&issuetype=1 
```

So maybe that link should point somewhere in jira instead?

**Comment by candita** [comment]
Thanks for the report. It has been fixed.
