### ISSUE TITLE
persistent ingresswithoutclassname alerts w/no ingresses present.

### ISSUE THREAD

**Issue by nate-duke** [openshift/cluster-ingress-operator#912]
We have an OKD 4.12 cluster which has persistent and increasing ingresswithoutclassname alerts with no ingresses normally present in the cluster. I believe the ingresswithoutclassname being counted is created as part of the ACME validation process managed by the [cert-manager](https://github.com/cert-manager/cert-manager) operator with it's [openshift route addon](https://github.com/cert-manager/openshift-routes) which are torn down once the ACME validation is complete.

Ingress cluster operator version:
> ingress                                    4.12.0-0.okd-2023-04-01-051724

![image](https://user-images.githubusercontent.com/40432118/234268549-209df47e-4e24-473b-b3b5-2baec4f794e6.png)
![image](https://user-images.githubusercontent.com/40432118/234268682-683f6ec0-374f-4ddb-98bb-1e516780d16c.png)

For example, one of these calls out `cm-acme-http-solver-46jbt`
![image](https://user-images.githubusercontent.com/40432118/234269911-43acc7ef-cfbc-4189-9e03-0ff1df789ad7.png)

however:
```
❯ kubectl -n openshift-route-controller-manager get ingress cm-acme-http-solver-46jbt
Error from server (NotFound): ingresses.networking.k8s.io "cm-acme-http-solver-46jbt" not found
```
and in fact:
```
❯ kubectl -n openshift-route-controller-manager get ingress
No resources found in openshift-route-controller-manager namespace.

❯ kubectl get ingress --all-namespaces
No resources found
```

I couldn't find a place in redhat's jira to post this so forgive me if this is the wrong place. I just noticed that the ingresswithoutclassname alert originated from this repo.

Happy to provide any further information if needed or file this issue elsewhere if it's more appropriate.

**Comment by candita** [comment]
Hi @nate-duke, can you check for Prometheus metrics using the expression `openshift_ingress_to_route_controller_ingress_without_class_name` ?  This is how the alert is generated.  Maybe there are some lingering metrics that aren't being cleaned up.

**Comment by nate-duke** [comment]
Hi @candita, thanks for looking into this. I did check that metric previously and it was steadily incrementing despite those cert-manager routes being created/destroyed. While I was doing the documentation to file this Issue we were updating our 4.12 cluster to the 4.12.0-0.okd-2023-04-16-041331 release and wouldn't you know it, after the update was complete the alerts all cleared.

Here's a 2 day snapshot of the sum of that metric though showing that it was >1 before but is 0 now. I'll have to see if it happens again once cert-manager has renewed a few certificates.

![image](https://user-images.githubusercontent.com/40432118/234564724-7778d980-e5b5-41f4-bb7b-04480f089c69.png)

**Comment by nate-duke** [comment]
@candita  ok, so good(?) news!  This came back after a few days:

![image](https://user-images.githubusercontent.com/40432118/235657665-3898ffe7-245f-4ec4-87ce-fc20ab1f011d.png)

However, only one classless ingress exists (the bottom one in the screenshot) which is unrelated and due to a users' poorly configured helm chart. The other two do not exist at all, yet are still alerting.

```bash
❯ kubectl get ingresses -A
NAMESPACE          NAME           CLASS    HOSTS                           ADDRESS                                            PORTS     AGE
REDACTED  REDACTED  <none>   REDACTED
```

They probably *did* exist at some point but the metric that's tracking them is just not getting cleaned up or decremented when they cease existing. I'm happy to help by providing any information you may need to help investigate this.

**Comment by nate-duke** [comment]
This metric does continue to increase. 3 days ago there were 3 (one that actually existed) today the metric is 8 and none exist.
![image](https://user-images.githubusercontent.com/40432118/236451890-5f228643-e3f5-4ce9-8e81-3f61f225bc4a.png)

```bash
❯ kubectl get ingresses -A
No resources found
```

Please let me know if you need any more information or if there is a more appropriate place to report this issue. Thanks!

**Comment by candita** [comment]
We have fixed the Issue button so you may now report this in our bug list if you'd like.  Our team will triage next week.  Thanks for the report.

**Comment by nate-duke** [comment]
No problem. Reported here: https://issues.redhat.com/browse/OCPBUGS-13181
