### ISSUE TITLE
invalid state in clusteroperator

### ISSUE THREAD

**Issue by abhinavdahiya** [openshift/cluster-ingress-operator#96]
https://github.com/openshift/installer/issues/1010 was reported where the creds provided to the cluster expired before the operator could create the DNS entry for `apps`. Although the creds expiry is fault of the installer.

The operator was reporting `Available: true` when clearly it had not completed its job
```console
$ oc get clusteroperator openshift-ingress-operator -o yaml
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  creationTimestamp: 2019-01-07T19:18:40Z
  generation: 1
  name: openshift-ingress-operator
  resourceVersion: "9771"
  selfLink: /apis/config.openshift.io/v1/clusteroperators/openshift-ingress-operator
  uid: 0a8bc0ad-12b1-11e9-b538-0a63a0bb21a6
spec: {}
status:
  conditions:
  - lastTransitionTime: 2019-01-07T19:18:40Z
    status: "False"
    type: Failing
  - lastTransitionTime: 2019-01-07T19:18:40Z
    status: "False"
    type: Progressing
  - lastTransitionTime: 2019-01-07T19:19:14Z
    status: "True"
    type: Available
  extension: null
  version: ""
```
as seen in the logs https://github.com/openshift/installer/files/2734351/ingress-operator.log while clearly it was failing...

@openshift/sig-network-edge

**Comment by Miciah** [comment]
We have three conditions:

    // OperatorAvailable indicates that the binary maintained by the operator (eg: openshift-apiserver for the
    // openshift-apiserver-operator), is functional and available in the cluster.

If the router deployment is in the desired state and is ready, then the router is functional; if DNS is not configured, does that mean the router is not available? That seems to be the assumption in this issue.

    // OperatorProgressing indicates that the operator is actively making changes to the binary maintained by the
    // operator (eg: openshift-apiserver for the openshift-apiserver-operator).

It would be a stretch to say that configuring DNS is "actively making changes to the binary", so this condition should be false if the router deployment is in the desired state, irrespective of DNS; agreed?

    // OperatorFailing indicates that the operator has encountered an error that is preventing it from working properly.
    // The binary maintained by the operator (eg: openshift-apiserver for the openshift-apiserver-operator) may still be
    // available, but the user intent cannot be fulfilled.

The phrase "user intent" is pretty broad, and I think it is fair to say that having DNS configured falls within its scope, so the "failing" condition should be true if DNS is desired but not configured; agreed?

**Comment by ironcladlou** [comment]
Any new status bugs should be opened in bz.
